import 'package:flutter/foundation.dart';
import 'package:zego_uikit/zego_uikit.dart';
import 'package:zego_uikit_prebuilt_call/zego_uikit_prebuilt_call.dart';
import 'package:zego_uikit_signaling_plugin/zego_uikit_signaling_plugin.dart';

import '../core/constants/zego_constants.dart';
import '../features/calling/call_config_builder.dart';
import '../models/call_model.dart';
import 'call_service.dart';

/// Owns the ZEGOCLOUD call-invitation service lifecycle (init/uninit) and
/// bridges its lifecycle callbacks to [CallService] Firestore writes, so
/// call history reflects what actually happened on a call.
///
/// Ownership rule to avoid duplicate/conflicting writes: the caller creates
/// the Firestore call doc and owns every status transition it can observe
/// unambiguously (accepted/declined/timeout/canceled/missed). The receiver
/// never writes for those, since it doesn't hold the Firestore doc id
/// directly. The one shared case is a call ending after it connected --
/// either side's device may be the one to observe that first (a clean
/// hangup via [_onCallEnd], or a network drop via [_onRoomStateChanged]) --
/// where the receiver resolves the same Firestore doc via `zegoCallId`
/// (see [CallService.endConnectedCall] / [CallService.disconnectConnectedCall]).
/// `zegoCallId` is ZEGOCLOUD's own `callID`: generated by the caller and
/// passed explicitly to `send(callID: ...)` (see `ContactsScreen._startCall`)
/// rather than left to auto-generate, so it's known immediately for the
/// Firestore write and guaranteed to match what the receiver reads back off
/// `ZegoCallInvitationData.callID` in `requireConfig`.
///
/// [_resolveCallEnd] is the single place either terminal path funnels
/// through, guarded by [_terminalWriteIssued], so a `ReconnectFailed`
/// immediately followed by the SDK's own `onCallEnd` for the same drop
/// can't double-write history for one call.
class CallingService {
  final CallService _callService;

  CallingService({required CallService callService})
    : _callService = callService;

  bool _initialized = false;

  /// Firestore doc id for the call this device is currently placing, if
  /// any. Set when this device sends an invitation; read by the
  /// invitation-event callbacks below to update that same doc.
  String? _outgoingCallId;
  DateTime? _connectedAt;
  Duration _lastKnownDuration = Duration.zero;

  /// The ZEGOCLOUD `callID` for whatever call this device is currently in
  /// (caller or receiver side), captured from `requireConfig`'s
  /// [ZegoCallInvitationData.callID]. This is the same ID the caller
  /// generates and writes as `zegoCallId` when creating the Firestore call
  /// doc (see [ContactsScreen._startCall]), so a receiver -- who never
  /// creates or holds that Firestore doc id -- can still resolve the same
  /// doc via [CallService]'s `zegoCallId`-keyed fallback writes.
  String? _currentZegoCallId;

  /// True once a terminal write for the current call has been issued, so a
  /// second callback firing for the same call (the SDK's contract is one
  /// terminal event per call, but this guards against it regardless) can't
  /// re-run a Firestore write for a call already resolved. Reset whenever a
  /// new call session starts (see [trackOutgoingCall] and `requireConfig`).
  bool _terminalWriteIssued = false;

  Future<void> init({required String userId, required String userName}) async {
    if (!ZegoConstants.isConfigured || _initialized) return;

    await ZegoUIKitPrebuiltCallInvitationService().init(
      appID: ZegoConstants.appId,
      appSign: ZegoConstants.appSign,
      userID: userId,
      userName: userName,
      plugins: [ZegoUIKitSignalingPlugin()],
      config: ZegoCallInvitationConfig(
        missedCall: ZegoCallInvitationMissedCallConfig(
          enabled: true,
          enableDialBack: false,
        ),
      ),
      notificationConfig: ZegoCallInvitationNotificationConfig(
        androidNotificationConfig: ZegoCallAndroidNotificationConfig(
          // Incoming calls should wake and cover the lock screen -- the
          // whole point of Bonus 2 -- rather than falling back to a normal
          // heads-up notification the user could miss.
          showOnLockedScreen: true,
          showOnFullScreen: true,
          callChannel: ZegoCallAndroidNotificationChannelConfig(
            channelID: ZegoConstants.notificationChannelId,
            channelName: ZegoConstants.notificationChannelName,
          ),
        ),
      ),
      requireConfig: (ZegoCallInvitationData data) {
        if (data.callID.isNotEmpty) {
          _currentZegoCallId = data.callID;
          _terminalWriteIssued = false;
        }
        return buildCallConfig(
          isVideoCall: data.type == ZegoCallInvitationType.videoCall,
          onDurationUpdate: (duration) => _lastKnownDuration = duration,
          // The invitation carries every invitee regardless of who ends up
          // building this config (caller or callee), so "more than one
          // invitee" reliably distinguishes a group call from 1-to-1 on
          // both sides -- no separate group-call signal needed.
          isGroupCall: data.invitees.length > 1,
        );
      },
      events: ZegoUIKitPrebuiltCallEvents(
        onCallEnd: _onCallEnd,
        room: ZegoCallRoomEvents(onStateChanged: _onRoomStateChanged),
      ),
      invitationEvents: ZegoUIKitPrebuiltCallInvitationEvents(
        onOutgoingCallAccepted: _onOutgoingCallAccepted,
        onOutgoingCallDeclined: _onOutgoingCallDeclined,
        onOutgoingCallRejectedCauseBusy: _onOutgoingCallRejectedCauseBusy,
        onOutgoingCallTimeout: _onOutgoingCallTimeout,
        onOutgoingCallCancelButtonPressed: _onOutgoingCallCanceled,
      ),
    );

    _initialized = true;
  }

  Future<void> uninit() async {
    if (!_initialized) return;
    await ZegoUIKitPrebuiltCallInvitationService().uninit();
    _initialized = false;
    _outgoingCallId = null;
    _currentZegoCallId = null;
    _connectedAt = null;
    _lastKnownDuration = Duration.zero;
    _terminalWriteIssued = false;
  }

  /// Records the Firestore doc created for a call this device just placed,
  /// so the callbacks below know which doc to update. Called from
  /// [ContactsScreen] right after a successful [CallService.createCall].
  /// [zegoCallId] is the same ID already passed to `send(callID: ...)`, so
  /// it's known immediately rather than waiting on `requireConfig`.
  void trackOutgoingCall(String callId, {required String zegoCallId}) {
    _outgoingCallId = callId;
    _currentZegoCallId = zegoCallId;
    _connectedAt = null;
    _lastKnownDuration = Duration.zero;
    _terminalWriteIssued = false;
  }

  void _onOutgoingCallAccepted(String callID, ZegoCallUser callee) {
    final callId = _outgoingCallId;
    if (callId == null) return;
    _connectedAt = DateTime.now();
    _writeCallStatus(
      () => _callService.updateCallStatus(callId, status: CallStatus.connected),
      context: 'onOutgoingCallAccepted',
    );
  }

  void _onOutgoingCallDeclined(
    String callID,
    ZegoCallUser callee,
    String customData,
  ) {
    _endOutgoingAs(CallStatus.rejected);
  }

  void _onOutgoingCallRejectedCauseBusy(
    String callID,
    ZegoCallUser callee,
    String customData,
  ) {
    _endOutgoingAs(CallStatus.rejected);
  }

  void _onOutgoingCallTimeout(
    String callID,
    List<ZegoCallUser> callees,
    bool isVideoCall,
  ) {
    _endOutgoingAs(CallStatus.missed);
  }

  void _onOutgoingCallCanceled() {
    _endOutgoingAs(CallStatus.missed);
  }

  void _endOutgoingAs(CallStatus status) {
    if (_terminalWriteIssued) return;
    final callId = _outgoingCallId;
    if (callId == null) return;
    _terminalWriteIssued = true;
    _outgoingCallId = null;
    _currentZegoCallId = null;
    _writeCallStatus(
      () => _callService.updateCallStatus(
        callId,
        status: status,
        endedAt: DateTime.now(),
      ),
      context: '_endOutgoingAs($status)',
    );
  }

  void _onCallEnd(ZegoCallEndEvent event, VoidCallback defaultAction) {
    _resolveCallEnd(wasConnected: _connectedAt != null);
    defaultAction();
  }

  /// Handles mid-call network loss. [Reconnecting]/[Reconnected] are
  /// transient states the SDK resolves on its own; only [ReconnectFailed]
  /// -- the SDK giving up on reconnecting -- is treated as a call outcome,
  /// distinct from a normal hangup ([_onCallEnd] fires separately once the
  /// SDK actually tears the room down for real).
  void _onRoomStateChanged(ZegoUIKitRoomState state) {
    if (state.reason != ZegoRoomStateChangedReason.ReconnectFailed) return;
    if (_connectedAt == null) return;
    _resolveCallEnd(wasConnected: true, disconnected: true);
  }

  /// Single resolution path for every way a connected/placed call can stop,
  /// shared by [_onCallEnd] and [_onRoomStateChanged] so the two can't both
  /// write a terminal status for the same call (e.g. a `ReconnectFailed`
  /// immediately followed by the SDK's own `onCallEnd` for the same drop).
  void _resolveCallEnd({
    required bool wasConnected,
    bool disconnected = false,
  }) {
    if (_terminalWriteIssued) return;
    _terminalWriteIssued = true;

    final durationInSeconds = _lastKnownDuration.inSeconds;
    final callId = _outgoingCallId;
    final zegoCallId = _currentZegoCallId;

    if (callId != null) {
      // Caller side: holds the Firestore doc id directly.
      _outgoingCallId = null;
      final status = !wasConnected
          ? CallStatus.failed
          : (disconnected ? CallStatus.disconnected : CallStatus.ended);
      _writeCallStatus(
        () => _callService.updateCallStatus(
          callId,
          status: status,
          endedAt: DateTime.now(),
          durationInSeconds: wasConnected ? durationInSeconds : null,
        ),
        context: '_resolveCallEnd(caller, $status)',
      );
    } else if (wasConnected && zegoCallId != null) {
      // Receiver side: never creates/holds the Firestore doc id, so it
      // resolves the same doc via the `zegoCallId` this device captured
      // from `requireConfig`'s ZegoCallInvitationData.callID -- the same
      // value the caller generated and wrote when creating the call (see
      // ContactsScreen._startCall). Only applies once connected -- a
      // receiver never creates/owns a "failed" (never-connected) write.
      final resolve = disconnected
          ? _callService.disconnectConnectedCall
          : _callService.endConnectedCall;
      _writeCallStatus(
        () => resolve(
          zegoCallId,
          endedAt: DateTime.now(),
          durationInSeconds: durationInSeconds,
        ),
        context: '_resolveCallEnd(receiver, disconnected=$disconnected)',
      );
    }

    _currentZegoCallId = null;
    _connectedAt = null;
    _lastKnownDuration = Duration.zero;
  }

  /// Runs a call-status Firestore write started from a synchronous SDK
  /// callback. Deliberately fire-and-forget rather than awaited -- these
  /// callbacks can't be async without changing the ZEGOCLOUD SDK's callback
  /// contract, and awaiting here would stall the call UI on a network write.
  /// The only requirement is that a failure can't be silent: it's caught and
  /// logged so it surfaces in development/crash reporting instead of being
  /// dropped as an unhandled Future error, while local calling state (reset
  /// by the caller before this runs) stays consistent regardless of whether
  /// the write ultimately succeeds.
  void _writeCallStatus(Future<void> Function() write, {required String context}) {
    write().catchError((Object error, StackTrace stackTrace) {
      debugPrint('CallingService: call-status write failed ($context): $error\n$stackTrace');
    });
  }
}
