// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQIi88sIZCF7lHgZLumz1Zgizi9h_j0b8',
    appId: '1:1003777902428:web:8dd7d1d61b4700e408e399',
    messagingSenderId: '1003777902428',
    projectId: 'sankar-group-335d2',
    authDomain: 'sankar-group-335d2.firebaseapp.com',
    storageBucket: 'sankar-group-335d2.firebasestorage.app',
    measurementId: 'G-VZ771N2YX6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB765Gru9s9jMYMq0F7FvSOWJxTDS53Mmc',
    appId: '1:1003777902428:android:8261c0d68bcdbe5208e399',
    messagingSenderId: '1003777902428',
    projectId: 'sankar-group-335d2',
    storageBucket: 'sankar-group-335d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0i6T4alTCVBGrdkixMfqcBF7fBdvXnKw',
    appId: '1:1003777902428:ios:44a8976fdd0f75d208e399',
    messagingSenderId: '1003777902428',
    projectId: 'sankar-group-335d2',
    storageBucket: 'sankar-group-335d2.firebasestorage.app',
    iosBundleId: 'com.connectcall.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0i6T4alTCVBGrdkixMfqcBF7fBdvXnKw',
    appId: '1:1003777902428:ios:58400097a18d577a08e399',
    messagingSenderId: '1003777902428',
    projectId: 'sankar-group-335d2',
    storageBucket: 'sankar-group-335d2.firebasestorage.app',
    iosBundleId: 'com.example.sankarGroup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQIi88sIZCF7lHgZLumz1Zgizi9h_j0b8',
    appId: '1:1003777902428:web:730c5b35dac401e508e399',
    messagingSenderId: '1003777902428',
    projectId: 'sankar-group-335d2',
    authDomain: 'sankar-group-335d2.firebaseapp.com',
    storageBucket: 'sankar-group-335d2.firebasestorage.app',
    measurementId: 'G-GT6QK9Y484',
  );
}
